### PR TITLE
Use dependency injection to get service instances

### PR DESCRIPTION
**Pull request by mlocati**
And the last one: instead of using static methods, what about using DI (dependency injection)?

This makes dependencies much more cleaner, and it simplify the code IMHO

### CODE REVIEW

**Review by marcokuoni — APPROVED** [review]
This is still magic for me? From where knows the TestGraphQl Class which instance of PersonResolver it has to take for the constructor?

**Comment by marcokuoni** [comment]
http://php-di.org/doc/autowiring.html
Ah ok, this works as long the instance of the parameter can be managed like a singleton. so when i don't add any parameter to the constructor he will create the parameters and hold it like a singleton some where in the php heaven.

**Comment by mlocati** [comment]
> From where knows the TestGraphQl Class which instance of PersonResolver it has to take for the constructor?

You have 3 options:

1. use a specific instance when you call `$app->make()`:
  ```php
   $app->make(TestGraphQl::class, ['personResolver' => $instance]);
   ```
2. register an instance in the app:
   ```php
   // This is usually done at startup, in the so-called service providers
   $app->bind(PersonResolver::class, function(Application $app) {
       return YourWayToCreateThePersonResolverInstance;
   });
   // This makes TestGraphQl use the instance provided by the method above
   $app->make(TestGraphQl::class);
   ```
1. let PHP create the instance (like in this PR):
   ```php
   $app->make(TestGraphQl::class);
   ```

**Comment by mlocati** [comment]
For example, `EntityManagerInterface` is registered by the core [`DatabaseServiceProvider`](https://github.com/concrete5/concrete5/blob/8.5.1/concrete/src/Database/DatabaseServiceProvider.php#L70).

**Comment by marcokuoni** [comment]
This is really amazing. Should be descriped somewhere on c5 doc. exactly like you did with the three option and the sample of EntityManagerInterface. Thanks a lot for the input

**Pull request merged**
